hydra:
  run:
    dir: hydra_output/

data:
  exp_name: test
  data_dir: ./input/resize_1024
  seed: 0
  img_size: &image_size 512
  n_splits: 5
  sub_th: 0.2
  rad_id: all  # Default: all  ex. R9, R10, R11   Set List

train:
  lr: 1e-4
  epoch: 10
  fold: 0
  batch_size: 6
  num_workers: 16
  weight_decay: 1e-5
  backbone: tf_efficientnet_b0_ns


aug_kwargs_detection:
  aug_train:
    RandomSizedBBoxSafeCrop: {"height": *image_size, "width": *image_size}
    HorizontalFlip: {"p": 0.5}
    VerticalFlip: {"p": 0.5}
    ShiftScaleRotate: {"scale_limit": 0.15, "rotate_limit": 10, "p": 0.5}
    RandomBrightnessContrast: {"p": 0.5}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  aug_val:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  aug_test:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}


aug_kwargs_classification:
  aug_train:
    RandomResizedCrop: {"height": *image_size, "width": *image_size, scale: [0.5, 1.0]}
    CLAHE : {"clip_limit": 4.0, "p": 0.5}
    HorizontalFlip: {"p": 0.5}
    ShiftScaleRotate: {"scale_limit": 0.15, "rotate_limit": 10, "p": 0.5}
    RandomBrightnessContrast: {"p": 0.5}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}
    CoarseDropout: {"max_holes": 15, "max_height": 12, "max_width": 12}

  aug_val:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  aug_test:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}
