hydra:
  run:
    dir: hydra_output/

comet_ml:
  api_key: LSTIie51umcysQtnef1Zzil6V
  project_name: vinbigdata-chest-x-ray

data:
  exp_name: test
  seed: 42
  img_size: 512
  n_splits: 5
  sub_th: 0.5

train:
  lr: 1e-4
  epoch: 20
  fold: 0
  batch_size: 16
  num_workers: 8
  weight_decay: 1e-5
  model_type: tf_efficientnet_b0_ns
  scheduler: cosine