hydra:
  run:
    dir: hydra_output/

data:
  data_dir: ./input/resize_1024
  output_dir: ./detectron2_output/exp01
  img_size: &image_size 1024
  # Ref: https://github.com/facebookresearch/detectron2/blob/master/detectron2/model_zoo/model_zoo.py
  backbone: COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml
  use_class14: False
  seed: 42
  use_classification: True
  score_th: 0.0
  rad_id: all  # Default: all  ex. R9, R10, R11   Set List
  split_method: valid_10  # valid_20 or all_train

classification_kwargs:
  data_dir_cls: ./input/resize_1024
  weight_dir: ./weights/
  upper_th: 0.985
  lower_th: 0.08

train:
  lr: 0.001
  max_iter: 60000
  num_workers: 16
  batch_size_per_image: 512
  ims_per_batch: 2

aug_kwargs_detection:
  Resize: {"height": *image_size, "width": *image_size}
  CLAHE : {"clip_limit": 4.0, "p": 0.5}
  HorizontalFlip: {"p": 0.5}
  VerticalFlip: {"p": 0.5}
  RandomRotate90: {"p": 0.5}
  RandomGamma: {"p": 0.5}
  ShiftScaleRotate: {"scale_limit": 0.15, "rotate_limit": 10, "p": 0.5}
  RandomBrightnessContrast: {"p": 0.5}
