hydra:
  run:
    dir: hydra_output/

data:
  exp_name: test
  seed: 42
  img_size: &image_size 512
  n_splits: 5
  sub_th: 0.2
  rad_id: [R9, R10]  # Default: all  ex. R9, R10, R11   Set List

train:
  lr: 1e-4
  epoch: 20
  fold: 0
  batch_size: 2
  num_workers: 8
  weight_decay: 1e-5
  backbone: tf_efficientnet_b2_ns


aug_kwargs:
  aug_train:
    RandomSizedBBoxSafeCrop: {"height": *image_size, "width": *image_size}
    HorizontalFlip: {"p": 0.5}
    VerticalFlip: {"p": 0.5}
    ShiftScaleRotate: {"scale_limit": 0.15, "rotate_limit": 10, "p": 0.5}
    RandomBrightnessContrast: {"p": 0.5}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  aug_val:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

  aug_test:
    Resize: {"height": *image_size, "width": *image_size}
    Normalize: {"mean": [0.485, 0.456, 0.406], "std": [0.229, 0.224, 0.225]}

aug_kwargs_detectron2:
  "HorizontalFlip": { "p": 0.5 },
  "ShiftScaleRotate": { "scale_limit": 0.15, "rotate_limit": 10, "p": 0.5 },
  "RandomBrightnessContrast": { "p": 0.5 }